### ISSUE TITLE
Rounding $23.45 to $24

### ISSUE THREAD

**Issue by MrTin** [kipcole9/money#101]
First, thanks for an awesome library!

I was digging through documentation and source code but couldn't find an option to do this, did I miss it or do you have an idea on how I can do this?

We use this inside our UI to make prices look less cluttered.

Thanks,
Martin

**Comment by Schultzer** [comment]
I would use `to_string/2` if you just want the formatting but not change the actual money struct.
https://hexdocs.pm/ex_cldr_numbers/2.6.0/Cldr.Number.html#to_string/2
```elixir
Money.to_string! Money.new("23.45", :USD), rounding_mode: :up
"$24"
```
You can use the same option with `Money.round/2`

https://hexdocs.pm/ex_money/Money.html#round/2
```elixir
Money.round Money.new("23.45", :USD), rounding_mode: :up
#Money<:USD, 24>
```

**Comment by kipcole9** [comment]
Thanks for the question.  As a result I noticed the documentation for `Money.to_string/2` wasn't complete - it didn't note that that `options` are passed to `Cldr.Number.to_string/3`.  Anyway, to answer your question, the following does what you ask:
```elixir
# Round up
iex> Money.to_string! Money.new("23.45", :USD), fractional_digits: 0, rounding_mode: :up
"$24"

# Rounding mode :down (ie truncate)
iex> Money.to_string! Money.new("23.45", :USD), fractional_digits: 0, rounding_mode: :down
"$23"

# Default rounding which his :half_even (bankers rounding)
iex> Money.to_string! Money.new("23.45", :USD), fractional_digits: 0
"$23"
```
In this case, ` fractional_digits: 0, rounding_mode: :up` are passed to `Cldr.Number.to_string/3`. 

There intentionally isn't a way to round the amount with less than the digits defined for a currency. That is, you can round:
```elixir
iex> Money.round Money.new("23.45678", :USD), rounding_mode: :up                    
#Money<:USD, 23.46>
```
But you can't round to less than 2 decimal digits (for USD).

There is an option for force the decimal digits value using `Money.put_fraction/2` but there is a bug if you specify `0`.  I'll fix the bug.  But even then, the number of digits still complies with the definition of the currency.
```
iex> Money.put_fraction Money.new("23.45", :USD), 99            
#Money<:USD, 23.99>

iex> Money.put_fraction Money.new("23.45", :USD), 1
#Money<:USD, 23.01>

# Bug when 0 digits.
iex> Money.put_fraction Money.new("23.45", :USD), 0 
#Money<:USD, 23.45>
```

**Comment by kipcole9** [comment]
Based on this issue I've [published Money 3.4.2](https://hex.pm/packages/ex_money/3.4.2) with the following changes:

### Bug Fixes

* `Money.put_fraction/2` now correctly allows setting the fraction to 0.

### Enhancements

* `Money.round/2` allows setting `:currency_digits` to an integer number of digits in addition to the options `:iso`, `:cash` and `:accounting`.  The default remains `:iso`.

* Improves the documentation for `Money.to_string/2`.

### Notes

Although you can now round to `0` decimal digits, the `Money.to_string/2` output will still have the precision of the currency unless you specify `:fractional_digits`.  For example:
```elixir
iex> money = Money.new(:USD, "23.67")       
#Money<:USD, 23.67>

iex> rounded = Money.round(money, currency_digits: 0)
#Money<:USD, 24>

# Will still apply default digits for fractional money
iex> Money.to_string! rounded
"$24.00"

# But forcing `:fractional_digits` allows 0 digits
iex> Money.to_string! rounded, fractional_digits: 0
"$24"
```

**Comment by MrTin** [comment]
Hrm, seems like we are getting different results. I just don't see the rounding doing anything right now.

This is what I get:
```elixir
Money.to_string! Money.new("23.45", :USD), rounding_mode: :up
# "$23.45"

Money.round Money.new("23.45", :USD), rounding_mode: :up
# #Money<:USD, 23.45>
```

Environment
```elixir
# Packages
{:ex_money, "~> 3.4.1"},
{:ex_cldr, "~> 2.6"},

# Config
config :ex_money,
  exchange_rates_retrieve_every: :never, # 300_000
  api_module: Money.ExchangeRates.OpenExchangeRates,
  callback_module: Money.ExchangeRates.Callback,
  exchange_rates_cache_module: Money.ExchangeRates.Cache.Ets,
  preload_historic_rates: nil,
  retriever_options: nil,
  log_failure: :warn,
  log_info: :info,
  log_success: nil,
  json_library: Jason,
  default_cldr_backend: Upgraded.Cldr
```

**Comment by kipcole9** [comment]
@MrTin Please see my response.  Unfortunately @LostKobrakai's recommendation isn't actually the solution in this case.

**Comment by kipcole9** [comment]
Appreciate the comment @MrTin, it helps with motivation for sure!
