### ISSUE TITLE
configuration documentation

### ISSUE THREAD

**Issue by mithereal** [kipcole9/money#102]
theres no information on how to set up the config option Cldr.Config.json_library(), im confused by this line should this be a file? or do i set the config up in mix?

**Comment by LostKobrakai** [comment]
It executes `Cldr.Config.json_library()`, which means money will use the same library as the one configured for `cldr`. It's highly likely you want both to use the same library.

**Comment by kipcole9** [comment]
Sorry for the slow response and thanks for the report.  I've updated the documentation and published the update to hex.

The updated section is at https://hexdocs.pm/ex_money/readme.html#json-library-configuration so please let me know if that clarifies or if you have any further suggestions.
