### ISSUE TITLE
Money Amount: sign, exp, coef output with Decimal undeclared?

### ISSUE THREAD

**Issue by njwest** [kipcole9/money#106]
Just upgraded from `ex_money 3.2` to `ex_money 4.1` + `ex_money_sql`, and this changed my Absinthe GQL money type output from `{ currency, amount: "88" }` to :
```javascript
{ 
  "currency", 
  "amount": {
      "sign": 1,
      "exp": 0,
      "coef": 88
   }
}
```

As identified by @LostKobrakai , this issue is the result of an upgrade to the Decimal package. `Decimal >= 1.6` results in the sign/exp/coef above.

Initially, I was not specifying a Decimal version in mix.exs (several of my deps use it), but after specifying and downgrading to 1.5, amount output returned to normal.

My Money GraphQL type definition:

```elixir
defmodule KaifongWeb.Schema.Types.Custom.ExMoney do
  @moduledoc """
  Ex Money scalar type
  """
  use Absinthe.Schema.Notation

  scalar :money, name: "ExMoney" do
    description("""
    Money type
    """)

    serialize(&encode/1)
    parse(&decode/1)
  end

  @spec decode(Absinthe.Blueprint.Input.String.t()) :: {:ok, term()} | :error
  @spec decode(Absinthe.Blueprint.Input.Null.t()) :: {:ok, nil}
  defp decode(%Absinthe.Blueprint.Input.String{value: value}) do
    with value <- Money.parse("USD" <> value) do
      {:ok, value}
    end
  end

  defp decode(%Absinthe.Blueprint.Input.Null{}) do
    {:ok, nil}
  end

  defp decode(_) do
    :error
  end

  defp encode(value), do: value
end

```

Money with currency PostgreSQL migration:
```elixir
defmodule Kaifong.Repo.Migrations.AddMoneyWithCurrencyTypeToPostgres do
  use Ecto.Migration

  def up do
    execute("CREATE TYPE public.money_with_currency AS (currency_code char(3), amount numeric);")
  end

  def down do
    execute("DROP TYPE public.money_with_currency;")
  end
end
```

Migrated from conversation in issue #104

**Comment by kipcole9** [comment]
Hmm, that's curious.  And I can't quite work out where that serialisation format is coming to in `Decimal` either.  I've confirmed that with `Jason` and `Poison` serialising a `Money` struct delivers a string-based amount.  Perhaps its an `Absinthe` version issue more than a `Decimal` version issue?  Any ideas?

**Comment by kipcole9** [comment]
I'd like to add using `Money` with `Absinthe` so when we get to the bottom of this I'll add it to the documentation (and ask you to review it before I publish since I haven't used `Absinthe`

**Comment by njwest** [comment]
Sure, can review

I don't think the problem is coming from Absinthe as my Absinthe-related deps have remained the same throughout all of this:

```elixir
      {:absinthe, "~> 1.4"},
      {:absinthe_plug, "~> 1.4"},
      {:absinthe_ecto, "~> 0.1.3"},
      {:absinthe_phoenix, "~> 1.4.0"},
``` 

I'm fairly certain the issue is from Decimal >= 1.6, as adding `{:decimal, "~> 1.5.0"},` to my mix.exs prevented another dependency from installing 1.6

In my haste to fix this, I did not check to see which dependency was doing this 😆 I think there were three

**Comment by kipcole9** [comment]
Appreciate the feedback.  I run my tests of Decimal > 1.5 without error and I can’t reproduce What you are seeing.  Very irritating. I looked the source code and commit log for Decimal and I can’t see anything jumping out at me there either. 

I’ll keep digging.

**Comment by njwest** [comment]
Hmm, I do have both `Jason` and `poison` in my mix.lock, and have had `{:jason, "~> 1.0"},` in mix.exs since starting this particular app

Sorry I can't contribute more to finding the source of this bug, I think it might be an edge case related to all of the dependencies I have been using that rely on `Decimal` and packages related to `Decimal`/GQL/`ecto`

Am super busy atm, but when I have some time I'll see if I can upload an example project that generates this same behavior

**Comment by njwest** [comment]
Okay, so it appears that the root is not Decimal 1.6, but having Decimal undeclared... I am declaring `{:decimal, "~> 1.6.0"},` in my mixfile with no issues

**Comment by LostKobrakai** [comment]
Can you consult mix.lock or `mix deps` if this change does also include a version change for any related dependencies? I cannot imagine that just adding that line would make a difference unless something else is wrong.
