### ISSUE TITLE
Do not depend on default_backend when the backend is explicitly passed

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/money#108]
Using `Keyword.get_lazy` and `Keyword.put_new_lazy` it is possible to not need to call for the `default_backend` and therefore not fail if it's not present (or needed).

Usecase is that I'd much rather have `MyApp.CldrBackend.Money.to_string` than needing configuration or passing opts. Basically like other cldr companion libraries work as well.

**Comment by kipcole9** [comment]
Great idea - I did not know about `get_lazy` or `put_new_lazy` and they are exactly what are required!  Thanks for the suggestion, I'll get on it. I've been puzzling over this lately so great timing too.

**Comment by kipcole9** [comment]
I've updated [ex_cldr](https://hex.pm/packages/ex_cldr/2.10.2) and [ex_cldr_numbers](https://hex.pm/packages/ex_cldr_numbers/2.7.2) to use `Keyword.get_lazy/3`. I've updated [ex_money](https://hex.pm/packages/ex_money/4.2.2) as well in the one place where the non-lazy version was being used with a `Cldr.default_backend/0`.

You would also like me to add a `Cldr provider` module that generates a `<backend>.Money` module with an api like the other `ex_cldr_*` packages?  Makes sense to me and it doesn't place a dependency on any of the other packages.  I'll work on this today if I've understood you correctly.

**Comment by LostKobrakai** [comment]
Yeah, having it as another provides was what I was thinking about.

**Comment by kipcole9** [comment]
Added in [ex_money version 4.3.0](https://hex.pm/packages/ex_money/4.3.0).  Just add `Money` to the list of providers for a backend.
