### ISSUE TITLE
Parsing thousand separators

### ISSUE THREAD

**Issue by Doerge** [kipcole9/money#112]
Awesome with a completely new parsing implementation! 🚀 

I found a small bug: Some locales have reversed the thousand and the decimal separators.
Old version (before new parser):
```
iex(1)> Money.parse("1,127.54 €", locale: "en")
#Money<:EUR, 1127.54>
iex(2)> Money.parse("1.127,54 €", locale: "de")
#Money<:EUR, 1127.54>
```
new version:
```
iex(1)> Money.parse("1,127.54 €", locale: "en")
#Money<:EUR, 1127.54>
iex(2)> Money.parse("1.127,54 €", locale: "de")
{:error, {Money.ParseError, "Could not parse \"1.127,54 €\"."}}
```

Additionally I think this should throw an error:
```
iex(1)> Money.parse("1.127,54 €", locale: "en")
#Money<:EUR, 1.12754>
```
because what is the semantic meaning of the `,`? It's clearly an error, either in input, or in locale choice.

**Comment by kipcole9** [comment]
Thanks for the comments and support.  The first issue is a parsing error which I'll look into today. Once parsed correctly there should be no issues in understanding the number itself in the `de` locale.

I don't believe the second part is a bug per se. [CLDR](https://unicode.org/reports/tr35/tr35-numbers.html#Special_Pattern_Characters ) does permit grouping symbols in the fractional part:
> The grouping separator may also occur in the fractional part, such as in “#,##0.###,#”. This is most commonly done where the grouping separator character is a thin, non-breaking space (U+202F), such as “1.618 033 988 75”. See physics.nist.gov/cuu/Units/checklist.html.

**Comment by kipcole9** [comment]
Fixed in master, thanks much for the report.  I will push a new release to hex by end of Sunday.

**Comment by Doerge** [comment]
Awesome, thanks!
Huh. Guess I learned something new about fractional thousand separators! 😁
