### ISSUE TITLE
[HELP] `Money.to_currency` throwing cert error

### ISSUE THREAD

**Issue by coladarci** [kipcole9/money#116]
Hey @kipcole9 sorry for pestering you twice in a day for two separate projects, but this one is a bit scary and I wanted to see if you happened to have any suggestions. 

In our staging env out of the blue, this started happening:

```
UndefinedFunctionError: function :tls_alert.exception/1 is undefined (module :tls_alert is not available)
  Module "tls_alert", in :tls_alert.exception/1
  File "lib/money.ex", line 1589, in Money.to_currency!/3
```

And around the same time, this started showing up:
```
MatchError: no match of right hand side value: {:error, {:tls_alert, {:certificate_expired, 'TLS client: In state certify at ssl_handshake.erl:1749 generated CLIENT ALERT: Fatal - Certificate Expired\n'}}}
  File "lib/utils/money.ex", line 18, in Utils.Money.usd_exchange_rate/1
```

This is only happening on stage, so it can't be the exchange rate service having problems, I wouldn't think (or else prod would be blowing up). I have to assume this is a problem w/ our  env and am speaking w/ those folks separately, but perhaps you'd want to see this stacktrace in case you want to try and handle it more gracefully?

As always, appreciate you,

**Comment by kipcole9** [comment]
This looks very related to the latest release of `ex_money` that added certificate verification to the API that calls external exchange rates services. Although I do test it (including live access to the open exchange rates API) I can't test all external services or all platforms.

`{:error, {:tls_alert, {:certificate_expired, 'TLS client: In state certify ...` definitely a surprise and would seem to suggest its the certificate of the exchange rates service you're using?

Perhaps your new code is using the updated `ex_money` and your `prod` isn't (unlikely I guess at this stage).

As you say, at minimum, I need to make sure this kind of error is handled better. I certainly would not have expected to see `:tls_alert` module not being found either so I need to dig into this.

On it now with my morning coffee.

**Comment by kipcole9** [comment]
If its an external and publicly accessible exchange rate service would you let me know which one so I can try it on my side?

**Comment by kipcole9** [comment]
heh - good news!  Sort of. I am getting the same error on my test suite so I suspect that the open exchange rates certificate may indeed have expired. Well of course not really good, but reproducible so I know where to go digging.

**Comment by kipcole9** [comment]
Next step, test with `curl` and I get:
```bash
kip@Kips-iMac-Pro thing % curl "https://openexchangerates.org/api/latest.json?app_id=f3bdf46d4a164a98be19a48d7c012a31"
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
Which is consistent with what I am seeing. And therefore it does indeed look like an issue on open exchange rates.

I have added a clause to detect this error and be more graceful than an exception but not clear I can do more at this stage except potentially provide an configuration option to *not* do certificate verification?  Seems like a bad idea though.  Thoughts?

**Comment by kipcole9** [comment]
I have logged a case with `openexchangerates.org`. Well, I used their contact form anyway.

**Comment by kipcole9** [comment]
I have published [ex_money version 5.2.0](https://hex.pm/packages/ex_money/5.2.0) that doesn't fix the issue since the underlying cause is an expired certificate at `openexchangerates.org` however it does handle the error better.  It also provides a configuration option `:verify_peer` which if set to false will disable certificate verification.  Clearly not something to be done lightly but will at least keep you going if you need do.

### Changelog

#### Enhancements

* Adds a configuration option `:verify_peer` which is a boolean that determines whether to verify the client certificate for any exchange rate service API call. The default is `true`. This option should not be changed without a very clear understanding of the security implications. This option will remain undocumented but supported for now.

#### Bug fixes

* Handle expired certificate errors on the exchange rates API service and log them. Thanks to @coladarci. Fixes #116

**Comment by coladarci** [comment]
I agree it should just be more graceful - I began questioning if my environment was broken, so simply confirming it’s a problem with the exchange rate service is all I will expect. Appreciate it!

**Comment by kipcole9** [comment]
This just in from the CEO of `openexchangerates.org`.  If you need to keep going I would recommend you set the `verify_peer: false` configuration option in `ex_money 5.2.0` just released.  You can do that without restarting the app (let me know if you want to do that and I'll walk you through it) - as long as you can get a remote console going.

> Hi Kip,

>Thank you for your enquiry and we're sorry to hear you are experiencing issues connecting to our API. While we are still investigating the issue, I can confirm that it relates to the Root Certificate provided by our SSL certificate authority, Comodo/Sectigo CA, which expired as of today (meanwhile our SSL certificate for *.openexchangerates.org, covering our website and API service, is valid until January 2021).

>We are currently working to clarify the steps that need to be taken to remedy this issue for clients that are affected, and will follow up with you as soon as we have any update.

>In the meantime, you may consider the following temporary workaround. Our API supports both HTTP and HTTPS connections, and although under normal circumstances we would always recommend using HTTPS to connect to our service, if it is possible for you to temporarily modify your integration to use plain HTTP, this should correct the problem until a permanent solution is in place.

>I understand this isn't an ideal solution, however it may offer a temporary workaround to prevent business interruption while we are addressing the issue with the Root CA.

>Kind regards,



>William J. Crowcroft
--
Founder & CEO
support@openexchangerates.org
https://openexchangerates.org

**Comment by kipcole9** [comment]
The certificate for `openexchangerates.org` has been replaced and the `ex_money` test suit passes without errors or exceptions. Very responsive support from them over the weekend.
