### ISSUE TITLE
could not find an app file at "_build/dev/lib/ex_money/ebin/ex_money.app"

### ISSUE THREAD

**Issue by niccolox** [kipcole9/money#121]
I am getting this on Mac and Ubuntu

```
Unchecked dependencies for environment dev:
* ex_money (Hex package)
  could not find an app file at "_build/dev/lib/ex_money/ebin/ex_money.app". This may happen if the dependency was not yet compiled or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies
```

mix.exs
```
      {:ex_money, "~> 5.4"},
```

applications
```
      :ex_money,
```

versions
```
elixir -v
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Elixir 1.10.2 (compiled with Erlang/OTP 22)
```

**Comment by kipcole9** [comment]
I suspect that having `ex_money` in your `:applications` key may be the issue.  These days you shouldn't need to do anything except add it to `deps` as you have done.

Would you mind removing `ex_money` from `applications` and trying again?

**Comment by niccolox** [comment]
OK, than and get the same error first time I try mix phx.server, second time I restart it runs

```
  866  MIX_ENV=dev mix deps.clean --all
  867  MIX_ENV=dev mix deps.get --all
  868  MIX_ENV=dev iex -S mix phx.server

errors

  874  MIX_ENV=dev iex -S mix phx.server

works
```

**Comment by kipcole9** [comment]
Thats unusual and I haven't seen it before, apologies that you're treading a new path.  I'll keep the issue open for a while in case you see a reoccurence.

**Comment by niccolox** [comment]
thanks, closing

**Comment by phil-a** [comment]
Seeing this issue, but for me it only showed up for me when running `MIX_ENV=prod mix compile` and getting the following:

```
Generated ex_money_sql app
==> phoenix_ecto
Compiling 7 files (.ex)
Generated phoenix_ecto app
==> <your-app-name>
Unchecked dependencies for environment prod:
* ex_money (Hex package)
  could not find an app file at "_build/prod/lib/ex_money/ebin/ex_money.app". This may happen if the dependency was not yet compiled or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies
```

It happens the first time when I run mix.compile, but if I re-run it a second time it compiles successfully.
Running Elixir 1.12.0 (compiled with Erlang/OTP 22)

**Comment by kipcole9** [comment]
Thats very strange. `ex_money` is definitely a dependency and yet its not being compiled (it should compile before `ex_money_sql`).  Any chance your repo is public so I can try to reproduce and debug?  Does it in fact compile `ex_money` first (your snippet above seems to be cut after the start of the compilation run)?

**Comment by phil-a** [comment]
It is not public, but I don't mind sharing the private repo with you. I followed along during the compilation and it doesn't look like it compiles ex_money at all on the first run. I can see __build/prod/lib/ex_money_sql/ebin/ex_money_sql.app_ is built, but not __build/prod/lib/ex_money/ebin/ex_money.app_

The following gist shows a dokku build, but getting the same error building prod locally as well:
https://gist.github.com/phil-a/cab67e3ff7e237167ad601e7cffc2dbf

**Comment by kipcole9** [comment]
Looking at the log of the gist you sent (thanks, very helpful) I think the issue is related to your `mix.exs` configuration which has:
```elixir
      {:money, "~> 1.8"},
      {:ex_money_sql, "~> 1.0"},
      {:ex_cldr, "~> 2.0"},
```

* `:money` is a different lib to `:ex_money` (mine is `:ex_money) and this is causing the module clashes you see since both libraries use the `Money` module name.

* `:ex_money_sql` pulls in `ex_money` which in turn pulls in `ex_cldr` so you probably only need to have:

```elixir
      {:ex_money_sql, "~> 1.0"},
```
Any chance you could give that a try and see if you see the error still?

**Comment by phil-a** [comment]
Think this was related to same issue as #128 (or at least the same solution). After I made that change I've rebuilt several times and have yet to see that error.
