### ISSUE TITLE
Parse DKK with locale da fails

### ISSUE THREAD

**Issue by Doerge** [kipcole9/money#125]
Hey Kip,

As far as I understand this should work:

    iex(1)> Cldr.Currency.strings_for_currency :DKK, "da", MyApp.Cldr
    ["kr", "dkk", "danske kroner", "dansk krone"]
    iex(2)> {:ok, s} = Money.to_string(Money.new(:DKK, 4200), locale: "da")
    {:ok, "4.200,00 kr."}
    iex(3)> Money.parse(s, locale: "da")
    {:error, {Money.ParseError, "Could not parse \"4.200,00 kr.\"."}}

The dot in "kr." is the culprit:

    iex(4)> Money.parse("4.200,00 kr", locale: "da")
    #Money<:DKK, 4200.00>

I have a hard time finding an authoritative reference for it, but I believe including the dot is the correct currency sign in the danish locale.

**Comment by kipcole9** [comment]
I agree, i would expect that any of the `Cldr.Currency.strings_for_currency/3` strings would be acceptable when parsing. I will work on a fix but it might be a couple of days.  Let me know if that's ok for you - if you need a fix in a hurry I will see if I can change some priorities.

**Comment by Doerge** [comment]
A couple of days is phenomenal support time for an open source project! 🎉

**Comment by kipcole9** [comment]
This [commit](https://github.com/kipcole9/money/commit/20e77acb3af11a34c7ff1a9ca8a5e5460d97720b) fixes the parsing issue. I have published [ex_money version 5.5.3](https://hex.pm/packages/ex_money/5.5.3) which has the following changelog entry:

### Bug Fixes

* Fixes parsing money when a currency string has a "." in it such as "kr.". Thanks for the report to @Doerge. Closes #125.

Thanks for the report and sorry for the inconvenience.
