### ISSUE TITLE
mix release - Duplicated modules specified in ex_money and money

### ISSUE THREAD

**Issue by phil-a** [kipcole9/money#128]
Hi, I have a project set up which is working properly on dev environment, and I'm trying to build a release using. Using the following packages in my mix file:
```
      {:money, "~> 1.8"},
      {:ex_money_sql, "~> 1.0"},
      {:ex_cldr, "~> 2.0"},
```

Running `MIX_ENV=prod mix release` results in the following error:

```
$ MIX_ENV=prod mix release
* assembling <app-name>-0.1.0 on MIX_ENV=prod
* using config/releases.exs to configure the release at runtime
** (Mix) Duplicated modules:
	'Elixir.String.Chars.Money' specified in ex_money and money
	'Elixir.Phoenix.HTML.Safe.Money' specified in ex_money and money
	'Elixir.Money.Ecto.Map.Type' specified in ex_money_sql and money
	'Elixir.Money.Ecto.Composite.Type' specified in ex_money_sql and money
	'Elixir.Money.Currency' specified in ex_money and money
	'Elixir.Money' specified in ex_money and money
```

I'm using Elixir 1.12.1 (compiled with Erlang/OTP 24)

Any help resolving this would be greatly appreciated!

**Comment by kipcole9** [comment]
Your `mix.exs` specifies `:money` when it should be `:ex_money`. Its not possible to use both `:money` and `:ex_money` in the same project.

**Comment by kipcole9** [comment]
I believe there is a lot of similarity in the basic APIs of the two libs so if there is something that is a barrier to moving from `:money` to `:ex_money` please let me know and I'll see what's possible.

**Comment by phil-a** [comment]
Ah! That's definitely it. Been jumping around between Github and Hex packages, seemed to have mixed up the packages! Thank you.

**Comment by kipcole9** [comment]
Glad that sorted it out. Also you only need to specify `ex_money_sql`. `ex_money` and `ex_cldr` will be pulled in as transitive dependencies. Its also less error prone :-)

**Comment by phil-a** [comment]
That makes sense. Not sure what I was thinking, must have been one of those days. Thanks again!

**Comment by phil-a** [comment]
> I believe there is a lot of similarity in the basic APIs of the two libs so if there is something that is a barrier to moving from `:money` to `:ex_money` please let me know and I'll see what's possible.

And thank you for the offer but there's zero barrier! I preferred ex_money anyway and had already set everything up using it (I just mixed up package names). Appreciate all the hard work in building and maintaining this!
