### ISSUE TITLE
Proposal to_currency_code

### ISSUE THREAD

**Issue by Adzz** [kipcole9/money#130]
Hello 👋  love the lib

Would we be open to a `to_currency_code` a la the `to_decimal` function?

```elixir
@spec to_currency_code(money :: Money.t()) :: String.t()
def to_currency_code(%Money{currency: currency}) do
  currency
end
```

This would mean I don't have to reach into the struct to get the currency field which feels a little like crossing some abstraction boundary.

**Comment by kipcole9** [comment]
Thanks for the suggestion. Done!  Published [ex_money version 5.6.0](https://hex.pm/packages/ex_money/5.6.0) with the following changelog entry:

### Enhancements

* Adds `Money.to_currency_code/1` to return the currency code part of a `t:Money`. Thanks to @Adzz for the proposal. Closes #130.

Thanks for the support and encouragement!
