### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by DaTrader** [kipcole9/money#134]
Hi Kip,

Has it been thought through on how to benefit from the Money library in a use case where it's absolutely redundant to use Money instances even in memory-only given the fact that each single instance out of potentially tens of thousands or more instances (of money) that are present in the data model are of the same currency and identical formatting?

As I haven't yet had the time to delve deeper into the Money source code, do you find it feasible performance-wise to store (memory and DB -wise alike) the Decimals, while creating Money instances on demand for computation purposes only, or do you find the Money library as such too heavyweight in general for one such use-case?

Thanks,

Damir

**Comment by kipcole9** [comment]
Note that in any implementation using integers, precision has to be fixed so all integers can be interpreted correctly. We could also encode a precision in the integer but thats likely too complex and the law of diminishing returns probably applies.

The practical implication is that for sum and subtraction there should be no issue. For multiplication I think it's still ok. Division is most definitely a problem - or at least would be incompatible with the current `ex_money` implementation. The current implementation defers rounding to the currencies digits to the very last possible moment so precision can be preserved.  Thats not going to be possible in an integer implementation. My understanding is that financial institutions expect to retain at least 7 decimal digits of precision and I don't believe that can be maintained any of these proposals.

If the experiments prove positive, I'll probably implement them as a new but complementary library. Which, assuming the benchmarks prove out, I'll call "ex_fast_money".  This  will make clear the guarantees are different.

**Comment by kipcole9** [comment]
The results above bugged me, I didn't think the results should vary so much.  Its challenging with fast loops of course, and the median of 0 ns above with such big deviation illustrates that. I decided to try running the benchmark over a longer period of time so see if the results stabilise. And being on OTP 24 with the JIT to see if that produces a change over the longer time too. 

It does look like all three implementations converge quite closely when run longer, at least when calling `new/1` in which the packing of either the integer or the bitstring is the dominant performance point. Memory utilisation remains lowest on the packed decimal implementation as expected.

```
Benchmark suite executing with the following configuration:
warmup: 2 s
time: 1 min
memory time: 4 s
parallel: 1
inputs: none specified
Estimated total run time: 3.30 min

Benchmarking Bitstring Decimal...
Benchmarking Decimal...
Benchmarking Packed Decimal...

Name                        ips        average  deviation         median         99th %
Decimal                  4.45 M      224.84 ns ±45237.16%           0 ns        1000 ns
Bitstring Decimal        4.13 M      242.28 ns ±40507.71%           0 ns        1000 ns
Packed Decimal           4.02 M      248.55 ns ±21506.50%           0 ns        1000 ns

Comparison: 
Decimal                  4.45 M
Bitstring Decimal        4.13 M - 1.08x slower +17.44 ns
Packed Decimal           4.02 M - 1.11x slower +23.70 ns

Memory usage statistics:

Name                 Memory usage
Decimal                      96 B
Bitstring Decimal           128 B - 1.33x memory usage +32 B
Packed Decimal               64 B - 0.67x memory usage -32 B
```
