### ISSUE TITLE
Money.from_integer spec doesn't agree with output

### ISSUE THREAD

**Issue by jdewar** [kipcole9/money#136]
spec for `from_integer` error is a 3-tuple, but the output in the case of an error is a 2-tuple with a 2-tuple in the second slot.

spec says: `from_integer(integer(), currency_code(), Keyword.t()) :: t() | {:error, module(), String.t()}`

iex says:
```
iex(2)> Money.from_integer(1000, :UD) 
{:error, {Cldr.UnknownCurrencyError, "The currency :UD is invalid"}}
```

**Comment by kipcole9** [comment]
Thanks for the report. I have published [ex_money version 5.7.2](https://hex.pm/packages/ex_money/5.7.2) with the following changelog entry:

### Bug Fixes

* Fix spec for `Money.from_integer/3`. Thanks to @jdewar for the report.

### Enhancements

* Support a `:fractional_digits` option for `Money.from_integer/3` and improve the documentation.
