### ISSUE TITLE
Dependency tree issue with optional ex_money

### ISSUE THREAD

**Issue by maltoe** [kipcole9/money#142]
Hi,

we have a small (mostly internal) [library](https://github.com/bitcrowd/bitcrowd_ecto/pull/32) where I'm trying to add `ex_money` as an optional dependency and `ex_money_sql` (alongside Ecto) as a `only: [:dev, :test]` dependency for development and tests. Running into the following error I can't really make sense of:

```
$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  cldr_utils 2.19.1
  connection 1.1.0
  db_connection 2.4.2
  decimal 2.0.0
  digital_token 0.4.0
  ecto 3.8.4
  ecto_sql 3.8.3
  ex_cldr 2.33.2
  ex_cldr_currencies 2.14.1
  ex_cldr_numbers 2.27.2
  ex_money 5.12.1
  ex_money_sql 1.7.2
  jason 1.4.0
  nimble_parsec 1.2.3
  postgrex 0.16.4
  telemetry 1.1.0
Dependencies have diverged:
* jason (Hex package)
  the :only option for dependency jason

  > In deps/ex_money_sql/mix.exs:
    {:jason, "~> 1.0", [only: [:dev, :test], env: :prod, hex: "jason", repo: "hexpm", optional: false]}

  does not match the :only option calculated for

  > In deps/digital_token/mix.exs:
    {:jason, "~> 1.0", [env: :prod, hex: "jason", repo: "hexpm", optional: false]}

  Remove the :only restriction from your dep
** (Mix) Can't continue due to errors on dependencies
```

This can be easily reproduced by creating an empty mix project and setting the following dependencies

```
  defp deps do
    [
      {:ex_money, "~> 5.12", optional: true},
      {:ex_money_sql, "~> 1.7", only: [:dev, :test]}
    ]
  end
```

`digital_token` is a dependency of `ex_money` and hence doesn't have the `only` option set, so the error is technically correct. Adding `only: [:dev, :test]` to `ex_money` too fixes the problem, but it feels like that is not what I'm trying to express? Do you have a vague idea what mix is trying to tell me?

Sorry for abusing the issue tracker a bit, as this is likely not an issue with `ex_money` itself. Figured I could make use of your vast expertise, though :)

Thank you & have a nice day,
malte

**Comment by kipcole9** [comment]
@maltoe sorry for the inconvenience. I'll look into this but I observe a couple of things:

1. `ex_money` cannot be `optional: true` is you have also configured `ex_money_sql`. `ex_money_sql` depends on `ex_money`.
2. You should only have to configure `ex_money_sql`. It will pull in `ex_money` as a transitive dependency.

Therefore your deps should look like:
```elixir
def deps do
  {:ex_money_sql, "~> 1.7", only: [:dev, :test]}
end
```
Perhaps you could try that and see if the issue resolves itself?

**Comment by maltoe** [comment]
It does resolve the mix error, but I don't think it covers the semantics I'm trying to express. Maybe should have been clearer on my use-case:

* The library is a set of Ecto utils we use for our projects, among them custom validators.
* One of the validators works with money types (on Ecto schemas)
* Technically clients of this library would only need to pull in `ex_money` to be able to use this validator. We don't want to add `ex_money` as a hard dependency, hence the `optional: true`
* `ex_money_sql` we only need within the library itself for testing purposes (`TestRepo`).

Admittedly, one could argue that all clients of this library will also depend on `ex_money_sql` (as how else would they get a `Money` value into an Ecto schema)... But if it wasn't a schema-related function, I'd say this combination of `ex_money` and `ex_money_sql` deps should be possible.

Needless to say, removing the `ex_money_sql` dependency entirely fixes the issue, so it is possible to optionally depend on `ex_money`. Only then I can't use it in the tests anymore :)

---

Just found out, that setting both `optional: true` works as well.

```elixir
      {:ex_money, "~> 5.12", optional: true},
      {:ex_money_sql, "~> 1.7", optional: true}
```

I think that's what I'm going with for now, but IMO it doesn't make sense semantically.

Thanks for your insights though.

**Comment by maltoe** [comment]
hmm

```elixir
      {:ex_money, "~> 5.12", only: [:dev, :test], optional: true},
      {:ex_money_sql, "~> 1.7", only: [:dev, :test], override: true}
```

works and doesn't cascade. What do you think?

**Comment by kipcole9** [comment]
I haven't had a chance to dive into this yet to understand the desired semantics you're after.  But while I have a moment ... don't forget that `mix.exs` is just code so you can:
```elixir
def deps do
  if some_condition_test() do
    [
      {:ex_money, "~> 5.12", only: [:dev, :test], optional: true},
      {:ex_money_sql, "~> 1.7", only: [:dev, :test], override: true}
    ]
  else
    [
      {:ex_money, "~> 5.12", only: [:dev, :test], optional: true}
    ]
  end
end
```
I won't be able to dive deeper for maybe the next 12 hours or so but I will looker deeper then.

**Comment by maltoe** [comment]
You're right, this is a solution as well:

```elixir
defp deps(:prod) do
  [{:ex_money, "~> 5.12", optional: true}]
end

defp deps(_) do
  [
    {:ex_money, "~> 5.12"},
    {:ex_money_sql, "~> 1.7"}
  ]
end
```

In other words, abandoning the `:only` option altogether. :shrug:

**Comment by kipcole9** [comment]
That feels like it represents the semantics you are after quite cleanly. But I will still work out why the original configuration fails dependency resolution. I'll leave the issue open until then.

**Comment by maltoe** [comment]
Late night update. Using this issue for documentation, too, hope you don't mind the noise.

#### hex.build runs in current `MIX_ENV`

Last solution above worked until I published the package to hex. Apparently when you the package is built (`hex.build`, `hex.publish`) the `mix.exs` file is evaluated in the current environment (= `:dev` if `MIX_ENV` is unset). Now I'm considering asking people to always set `MIX_ENV=prod` when publishing this package or providing a script that does, but it seems a bit fragile, IMO. Or is that a convention we should have been following all along anyway? Publish packages in `prod`?

#### `override: true` on dev dependency does not work

Contrary to what I thought earlier in https://github.com/kipcole9/money/issues/142#issuecomment-1246357600 , setting `override: true` on the dev dependency does not fix the issue.

#### Following the original advise works

Didn't mention that before, but what does work is following mix' hint to "remove the :only restriction from your dep", i.e. in this case `Jason`. In other words, explicitly listing Jason as another optional dependency solves the issue:

```elixir
      {:ex_money, "~> 5.12", optional: true},
      {:ex_money_sql, "~> 1.7", only: [:dev, :test], override: true},
      {:jason, "~> 1.0", optional: true}
```

I kind of knew this would work, but it feels awfully unpleasant to add random dependencies from "down the tree" to your top-level list for reasons like this. Client apps will also see it, so I probably should relax the version requirement to `> 0` or so. LBNL, it's of course pure luck that it is _only_ Jason this time.

#### Conclusion

IMO mix should be smart enough to override Jason's mismatching `only` option from the optional top-level `ex_money` specification. Not sure why it can't. Adding Jason in this case should be ok for now.

Thanks again for your help.

**Comment by maltoe** [comment]
@kipcole9 I think you can close this, it's just not an `ex_money` issue. Also, for reference, you can generally ignore the `:optional` keyword in the posts above, as

```
      {:ex_money, "~> 5.12"},
      {:ex_money_sql, "~> 1.7", only: [:dev, :test]}
```

produces the same error.

Generalized: If you have two dependencies `A` and `B` with different `:only` options, and both depend on a `C` package, `mix` will fail resolution and recommend to list `C` explicitly in your dependencies and specify/remove the `only` option.

Relevant code is [here](https://github.com/elixir-lang/elixir/blob/main/lib/mix/lib/mix/dep.ex#L342-L354), though I couldn't figure out where the `divergedonly` is actually calculated.

**Comment by kipcole9** [comment]
Good to know and I really appreciate all the work you did hunting this down.  Maybe a PR or issue for Hex would be appropriate?  I'll close the issue now as you suggest but feel free to open again if you see something I can fix better in `ex_money`.
