### ISSUE TITLE
Name Collision with :money

### ISSUE THREAD

**Issue by the-destro** [kipcole9/money#148]
Even though it is name :ex_money in hex it defines a module Money. This ends up causing a collision with the :money package

**Comment by kipcole9** [comment]
@the-destro you're right, definitely a module name clash. If I was starting again I'd probably chose something else but this project first commit was on June 25, 2016 so changing it now isn't really an option. I appreciate this is not helpful for you - but its also only the second time in 7 years this has come up.

I am curious though, what the environment and requirement that causes both `:money` and `:ex_money` to be configured?

**Comment by kipcole9** [comment]
I think there is far intersection of API compatibility in the two (and a fair amount in difference). So if you let me know where there is something in `:money` you can't see in `:ex_money` I'll certainly take a look at that.

**Comment by the-destro** [comment]
No worries. If we had started with ex_money and ex_money_sql we would probably be fine. I was wanting the nice currency conversion stuff from ex_money but I can roll my own. Thank you for your answer though
