### ISSUE TITLE
5.12.4 Not Released?

### ISSUE THREAD

**Issue by tomciopp** [kipcole9/money#149]
Looks like it was supposed to be released back in January, but there is nothing listed on hex. Any updates?

**Comment by kipcole9** [comment]
You're right, I did intend to release it in January and didn't. I've rerun tests and dialyse on updated deps and published it just now. Its definitely a very minor release but next will I will release version 5.13.0-rc.0 which updates the requirement on `ex_cldr_numbers` to a versions that uses [CLDR 43](https://cldr.unicode.org/index/downloads/cldr-43) data so its appropriate to release this now as the last version on CLDR 42 data. 

Thanks for the prompt!
