### ISSUE TITLE
Fractional digits of currency not being honored by default for `Money.to_string`

### ISSUE THREAD

**Issue by dhedlund** [kipcole9/money#151]
This appears to be related to changes with fractional digits in the `ex_cldr_numbers` 2.31.3 release. There have also been changes in `ex_money` around fractional digits and how it interacts with that package, so I'm not sure where the bug is.

It appears that `Money.to_string` now always formats using 2 fractional digits by default, even when the associated CLDR currency has 0 or 3 fractional digits; always using 2-digits might be based on my default locale, but it is still a change in behavior from previous versions and produces output that also doesn't match some of the [examples](https://github.com/kipcole9/money/blob/master/lib/money.ex#L748-L749) in the documentation.

Older versions of Money that use `ex_cldr_numbers` 2.31.2 produce:
```elixir
iex> Map.take(Cldr.Currency.currency_for_code!(:JPY), [:digits, :iso_digits, :cash_digits])
%{cash_digits: 0, digits: 0, iso_digits: 0}

iex> Money.to_string!(Money.new(:JPY, "1234"))
"¥1,234"

iex> Map.take(Cldr.Currency.currency_for_code!(:TND), [:digits, :iso_digits, :cash_digits])
%{cash_digits: 3, digits: 3, iso_digits: 3}

iex> Money.to_string!(Money.new(:TND, "1234"))
"TND 1,234.000
```

Newer versions of Money that use `ex_cldr_numbers` 2.31.3 or 2.32.0 produce:
```elixir
iex> Map.take(Cldr.Currency.currency_for_code!(:JPY), [:digits, :iso_digits, :cash_digits])
%{cash_digits: 0, digits: 0, iso_digits: 0}

iex> Money.to_string!(Money.new(:JPY, "1234"))
"¥1,234.00"

iex> Map.take(Cldr.Currency.currency_for_code!(:TND), [:digits, :iso_digits, :cash_digits])
%{cash_digits: 3, digits: 3, iso_digits: 3}

iex> Money.to_string!(Money.new(:TND, "1234"))   
"TND 1,234.00"
```

Is this now expected behavior? If so, what would be the correct option to pass in to always format amounts so they are padded to the number of fractional digits for that currency like the original behavior?

**Comment by kipcole9** [comment]
@dhedlund you're right, definitely a bug and totally unacceptable. I don't know how the slipped in and got past my tests. I will fix that today and issue a new release of `ex_cldr_numbers` which is where the fault lies.

To be clear, tests do fail on `ex_money` but apparently I have no failing test in `ex_cldr_numbers` which I will make sure to add as part of this fix.

**Comment by kipcole9** [comment]
I've pushed a [commit to cldr_numbers](https://github.com/elixir-cldr/cldr_numbers/commit/6e22e52aabdcff2476dc5473c87cbd166c033a38) that reverts an intentional change I made in ex_cldr_numbers version 2.31.3. That was a bad change on my part.

I've now also published [ex_cldr_numbers version 2.32.1](https://hex.pm/packages/ex_cldr_numbers/2.31.1) with the fix. Please let me know if your tests are now passing?

I will also update `ex_money` to pass the required default `:fractional_digits` so that it will work with any version of `ex_cldr_numbers`.

**Comment by dhedlund** [comment]
Things look good again using the new 2.32.1 version of `ex_cldr_numbers`! Thanks! :partying_face:

Lightning fast response, always love using your packages! :zap: :heart:

**Comment by kipcole9** [comment]
Thanks for the kind words @dhedlund - and apologies for a brain fade in thinking it was better to honour the CLDR format for currencies rather than do the right thing for each currency.
