### ISSUE TITLE
Docs seem broken on hexdocs.pm

### ISSUE THREAD

**Issue by tomtaylor** [kipcole9/money#153]
Hey, thanks a lot for this library, it seems really well thought through! 

I noticed the [docs on HexDocs](https://hexdocs.pm/ex_money/readme.html) seem broken. Specifically the navigation doesn't render correctly and I can't scroll up and down the sidebar. When I run them locally they seem fine. Might be worth rebuilding them?

**Comment by kipcole9** [comment]
You're eighth, thanks for the heads-up.  I'll investigate right away.

**Comment by kipcole9** [comment]
Interesting that up to ex_doc version 0.30.5 everything is ok but the versions after that do not work (at least in Safari). I will need to isolate a bit better before I open an issue on the ex_doc repo.

**Comment by tomtaylor** [comment]
Thank you!
