### ISSUE TITLE
Add hex.pm package URL to GitHub Repo 

### ISSUE THREAD

**Issue by Nezteb** [kipcole9/money#155]
Mostly just for easy back-and-forth between Hex/HexDocs/GitHub. 😄 

Also I occasionally get the two big Elixir money libraries mixed up:
- https://hex.pm/packages/money
- https://hex.pm/packages/ex_money (this project)

Despite this repo being called `money`, the Hex package is `ex_money`. A project URL in the GitHub repo description might help others distinguish between the two. 😄 

This is the specific field I'm referring to:
![screenshot_2023-11-17_at_18 05 44@2x](https://github.com/kipcole9/money/assets/3588798/80573bb6-38f8-4a09-b30d-45bda2c81b03)

**Comment by kipcole9** [comment]
Good suggestion - done!
