### ISSUE TITLE
Why is the amount not the first argument?

### ISSUE THREAD

**Issue by ryanwinchester** [kipcole9/money#19]
This library looks very promising. Thanks for making this 👍 

However, it seems non-elixiry to have the amount value be the second argument, and seems like something you'd find more in erlang.

```elixir
Money.new(:USD, 100)
```

It kind of removes it from being useful in a pipe, in my opinion.

Just wondering if there was a specific reason for it?

**Comment by kipcole9** [comment]
Ryan, actually the arguments to `Money.new/2` can be either way around since the types are orthogonal.  For example:
```elixir
iex(1)> Money.new(:USD, 100)
#Money<:USD, 100>
iex(2)> Money.new(100, :USD)
#Money<:USD, 100>
```
Hope that helps in your case.  I'll make the documentation clearer.

**Comment by kipcole9** [comment]
Updated [release v0.4.2](https://hex.pm/packages/ex_money) is on hex.  Thanks for submitting the issue.
