### ISSUE TITLE
Documentation is incorrect (or) migration-generator is not working correctly

### ISSUE THREAD

**Issue by vraravam** [kipcole9/money#3]
As the title says, according to the documentation, there should be a migration that creates the type in Postgres that can be used to store Money/Currency objects. If this documentation is correct, then the migration is not generated when installing the package. Could this be fixed please?

**Comment by kipcole9** [comment]
Viajy, when you run `mix help` you should see:
```
mix local.hex            # Installs Hex locally
mix local.phoenix        # Updates Phoenix locally
mix local.public_keys    # Manages public keys
mix local.rebar          # Installs Rebar locally
mix money.gen.migration  # Generates a migration to create the :money_with_currency composite database type
mix new                  # Creates a new Elixir project
mix phoenix.digest       # Digests and compress static files
```
And then you can run:
```
mix money.gen.migration
```
Which will create the migration.  Then `mix ecto.migrate` as usual.  If for some reason you don't see `money.gen.migration` then doing `mix deps.compile ex_money --force` will typically make it turn up.  Perhaps I'm being to clever at trying to conditionally compile the migration and the data type depending on if Ecto is configured.  I will revisit.

**Comment by kipcole9** [comment]
If the above works you should see:
```
Kips-iMac:money_test kip$ mix money.gen.migration
Compiling 12 files (.ex)
Generated money_test app
* creating priv/repo/migrations
* creating priv/repo/migrations/20161211090037_add_money_with_currency_type_to_postgres.exs
Kips-iMac:money_test kip$ mix ecto.migrate

17:03:30.775 [info]  == Running MoneyTest.Repo.Migrations.AddMoneyWithCurrencyTypeToPostgres.up/0 forward

17:03:30.779 [info]  execute "  CREATE TYPE public.money_with_currency AS (currency_code char(3), amount numeric(20,8))\n"

17:03:30.785 [info]  == Migrated in 0.0s
```

**Comment by vraravam** [comment]
@kipcole9 : Nope, when I run `mix help`, this is part of what I see (since the tasks are alphabetically ordered, I'm not posting the full list)...
<img width="857" alt="screen shot 2016-12-11 at 5 27 20 pm" src="https://cloud.githubusercontent.com/assets/69629/21079930/3ea0d2de-bfc7-11e6-97bf-d8bd9ec2eeb4.png">

btw: I'm on the latest elixir, phoenix, etc

**Comment by vraravam** [comment]
New update: I blasted the whole `deps` and `_build` directories, re-fetched ALL the packages, recompiled all, and then the migration task shows up - weird!

**Comment by kipcole9** [comment]
Thanks for sticking with it.  Turns out that I need to add ecto as an optional dependency in order to force the right compile time order - that should fix the situation where the mix task doesn't show up.  I'll have that in the next version which should stables things quite a bit.

**Comment by vraravam** [comment]
maybe the `Decimal` as well (in case you don't have it already)?

**Comment by kipcole9** [comment]
Updated ex_money to v0.0.11 which appears to fix this issue.  Added Ecto as an optional dependency which ensures that Ecto is now compiled before ex_money and therefore the migration and postgres type will compile in the correct order.
