### ISSUE TITLE
Money.new with tuples or not

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/money#30]
The readme uses `Money.new` without tuples, the docs/code says it should with with one.

**Comment by kipcole9** [comment]
Hmmm. The tuple versions are there for the convenience of Ecto cast/dump.  It feels more natural to use the arity/2 functions to me.  Therefore perhaps makes sense to promote them as the public api and `@doc false` the arity/1 tuple versions?

**Comment by LostKobrakai** [comment]
Ah, didn't even notice `new/2` in the code. Yeah I'd rather clearly promote one api as public and the other as internal with `@doc false`. I'm also with you that the arity/2 version also the better candidate for the public api.
I even feel the variable param order is a bit complex, but I can totally see that being useful in creating money values in a pipeline.

Another option could be to rename the tuple version to `from_tuple` like e.g. the core datetime module does handle all it's "various formats -> datetime" options. Similarly in a way the ecto tuple does not generate something "new" because it's just another representation of the same.

**Comment by kipcole9** [comment]
I like the from_tuple idea, seems more consistent with std lib as you say.  Coming up for 11pm here so I'm going to take a break and fix that in the morning.  Appreciate all the comments/issues/bugs, thanks.

**Comment by kipcole9** [comment]
Released [version 0.6.0](https://hex.pm/packages/ex_money) on hex
