### ISSUE TITLE
Convert currency to past exchange rate

### ISSUE THREAD

**Issue by svileng** [kipcole9/money#34]
This is not an issue, just a feature request 🙏 

The OXR API supports [retrieving exchange rates for a specific day in the past](https://docs.openexchangerates.org/docs/historical-json). When converting financial information from different points in time in the past (especially Sales data), it would be correct to use the exchange rate for that specific day, not the current one.

It will be great to have an optional `Date` param for `to_currency/3` that allows us to specify a specific date, e.g.

```
Money.to_currency(~M[100]USD, :AUD, ~D[2017-01-01])
```

That would use the exchange rate for 1 January 2017.

It will be also nice to have the `Retriever` sync past exchange rates beforehand — in our case, most of the time we need the rates for the past 3 months, so having this as a customisable param would be a nice bonus.

**Comment by kipcole9** [comment]
Good suggestion @svileng, and much appreciated.  I have few additional thoughts around this (named exchange rates for one).  Let me collect those thoughts and I'll revert them here in the next 24 hours.

**Comment by kipcole9** [comment]
@svileng I'm going to work on this during the weekend.  I am thinking about the following API and would appreciate any comments you might have.

### Current API

The current API provides `Money.ExchangeRates.latest_rates/0`

### Proposed API additions

Add the function `Money.ExchangeRates.rates/1` which is invoked as

* `Money.ExchangeRates.rates(~D[2017-01-01])` to return retrieve exchange rates as of a certain date where the significance of the data is interpreted by the exchange rates retrieval service (i.e. issues of timezone and DST are interpreted by the exchange rate service like OXR.  Typically this would means the date would be interpreted in the GMT timezone).

* `Money.ExchangeRates.rates(:today)` would retrieve the rates  of the day as defined by `Date.utc_today/0`

* `Money.ExchangeRates.rates("2017 Budget Rate")` or `Money.ExchangeRates.rates(:2017_budget_rate)` to retrieve a named set of rates

* `Money.ExchangeRates.name_rates(%{"AUD" => 0.7, ...}, :budget_rate)` to name a set of rates

### Prefilling historic rates

As you suggested, its a reasonable idea to prefetch historic rates.  The proposed API is

* Add an additional callback to `Money.ExchangeRates` called `populate_historic_rates/2` which will be called by `populate_historic_rates(from_date, to_date)` during the initialisation phase of a configured exchange rates retriever.  This callback is expected to populate the `:ets` table that is holding the rates.  The `from_date` and `to_date` can be configured in `config.exs` and further updated in the `init/1` function of the retriever.

* Add an additional callback to `Money.ExchangeRates` called `get_rates/1` which will get the rates for a specific date. This will populate the rates in the `:ets` table as well as return to the user.  So I expect this will be a `GenServer.call` and synchronous with the client code.

**Comment by kipcole9** [comment]
@svileng I have added support for historic rates to the master branch on GitHub.  The details are in the CHANGELOG and README but to make it easy the following applies:

* A new config key, `:preload_historic_rates` lets you configure the date range of rates that will be retrieved when the the exchange rates service starts up.  You can specify a `Date.t`, a `Date.Range.t` or ` {Date.t, Date.t}` tuple.

* Functions `Money.ExchangeRates.retrieve_historic/1` and `Money.ExchangeRates.retrieve_historic/2` which will request a range of exchange rates to be retrieved at any time

* Function `Money.ExchangeRates.historic_rates/1` which can be used to return the historic rates and then fed to `Money.to_currency/3`.  For example:

```elixir
alias Money.ExchangeRates
Money.to_currency(Money.new!(:AUD, 100), :EUR, ExchangeRates.historic_rates(~D[2017-01-01]))
```
Your feedback would be most welcome.  To run from master, change the `deps()` function in your `mix.exs` to include:

```elixir
{:ex_money, git: "https://github.com/kipcole9/money.git"}
```
and then run `mix deps.get`

**Comment by svileng** [comment]
That's awesome — great work! I think the new functionality covers all use cases I had in mind and I quite like the API. I'll pull `master` later this week for a test run 👍

**Comment by kipcole9** [comment]
Thanks for the encouragement Svilen.  i’ve issued a new release on hex that contains the new functionality so no need to pull master.

I look forward to your feedback and suggestions when you have the time.

**Comment by kipcole9** [comment]
Just a note that I’m not using the bulk api of OXR since I don’t have an api key that lets me use it.  It would be more network efficient for large requests (but not economically more efficient).

Let me know if this becomes a requirement for you.
