### ISSUE TITLE
delay_before_first_retrieval appears to have been removed

### ISSUE THREAD

**Issue by ratbag98** [kipcole9/money#39]
Updated to latest release

```
# mix.lock
ex_money": {:hex, :ex_money, "0.9.0", "43d52ac8384228949b8f6284a610f54f76ba93b01e4659b52b67959e8790c74c", [:mix], [{:decimal, "~> 1.4", [hex: :decimal, repo: "hexpm", optional: false]}, {:ecto, "~> 2.1", [hex: :ecto, repo: "hexpm", optional: true]}, {:ex_cldr, "~> 0.13", [hex: :ex_cldr, repo: "hexpm", optional: false]}, {:ex_cldr_numbers, "~> 0.3", [hex: :ex_cldr_numbers, repo: "hexpm", optional: false]}], "hexpm"}
```

Retriever process now starts immediately. I'd been using the delay as a kludgy way to get the retriever to work in production (with a 0 delay) and not run in test (with a near-infinite delay).

Could you either reenable the delay or let me know a more, shall we say, "idiomatic" way to get the behaviour described?  Thanks.

**Comment by ratbag98** [comment]
Sorry, realised I was being lazy, I'll find a different way to start the retriever using config.

**Comment by kipcole9** [comment]
For my tests I use the following approach which you might also find helpful:
```elixir
  test "That rates_available? returns correctly" do
    assert capture_io(fn ->
      config = ExchangeRates.default_config
      {:ok, _pid} = Money.ExchangeRates.Retriever.start_link(Money.ExchangeRates.Retriever, config)
      assert ExchangeRates.latest_rates_available? == false
      :timer.sleep(@sleep_timer)
      assert ExchangeRates.latest_rates_available? == true
     end)
  end
```
Basically I start the retriever task with a test configuration just for the test(s) that need it. 

The old approach of having the delay was actually a lazy strategy on my part to work around what ultimately was a bug.  Having fixed the bug there didn't seem a good reason to keep the delay.

**Comment by ratbag98** [comment]
Thanks. I really wanted to avoid the retriever running at all in tests. So I plonked a variable in `test.exs` and added this to `application.ex` before the `Supervisor.start_link()`:

```elixir
children = case Application.get_env(:my_app, :run_exchange_rates_retriever, true) do
      true -> children ++ [supervisor(Money.ExchangeRates.Supervisor, [])]
      false -> children
    end
```

Ugly on so many levels, but it does the trick. Thanks for your help

**Comment by kipcole9** [comment]
I believe that each test runs in isolation in its own process and therefore in my example the retriever runs only for the life of the test its started in.  I haven't validated it with 100% certainty but it is the behaviour I'm seeing.  Of course if your approach is working thats a good thing too :-)
