### ISSUE TITLE
Is there a way to accept negative amounts?

### ISSUE THREAD

**Issue by justuseapen** [kipcole9/money#41]
I'm trying to implement this for a bill tracking application. Sometimes bills have negative balances. Is there a way to represent this with the custom Money type? Any ideas on a workaround?

**Comment by kipcole9** [comment]
@justus, no issue (that I'm aware of) using negative money amounts:
```elixir
iex> import Money.Sigil
iex> Money.new :USD, -100.0 
#Money<:USD, -100.0>
iex> Money.add ~M[-100]USD, ~M[50]USD
{:ok, #Money<:USD, -50>}
```
If you have examples where a negative amount is resulting in an error let me know and I'll fix it.

**Comment by kipcole9** [comment]
Ahhh, perhaps you're referring to currency formatting?  CLDR doesn't define number formats for negative numbers.  Which means `Cldr.Number.to_string/2` with a `:currency` option won't show the currency symbol.

Is that the case?

**Comment by kipcole9** [comment]
BTW, if you choose to use option 2 above there is a performance gain if you precompile the format mask.  You do that by specifying`:precompile_number_formats` in your config.exs. For example:

```elixir
config :ex_cldr,
  default_locale: "en-001",
  locales: ["root", "fr", "zh", "zh-Hant", "en", "en-GB", "bs", "pl", "ru", "th", "he", "af"],
  precompile_number_formats: ["#,##,##0.00¤;-##,##0.00¤"]
```

**Comment by justuseapen** [comment]
The issue was on my end. I was sanitizing a currency string ("-$121.21") and using a replace_prefix that failed. Thanks for the additional info! Sorry to bother!

**Comment by kipcole9** [comment]
No problem, glad you solved your issue.
