### ISSUE TITLE
Money.from_integer_exp/2

### ISSUE THREAD

**Issue by Schultzer** [kipcole9/money#44]
Hi,

I will like to propose a function which will take an integer value represented as the subunit
and then returns a `Money.t`
this will help us when we pulling the data from stripe which serve it in subunits.

the idea is that we use the currency code to determine the exponent.

# Example

```elixir
  def from_integer_exp(amount, currency) when is_integer(amount) do
    %{:ok, %{code: code, digits: digits}} = Cldr.Currency.currency_for_code(currency)
    sign = if amount < 0, do: -1, else: 1
    
    sign
    |> Decimal.new(abs(amount), -digits)
    |> Money.new(code)
  end
```

I believe that this also could be done in Money.new/2 but not sure if that's what you want,
let me know what you think about this.

**Comment by kipcole9** [comment]
Agreed and included as `Money.from_integer/2` in [hex version 1.1.3](https://hex.pm/packages/ex_money).

### Changelog entry

* Add `Money.from_integer/2` as the effective inverse of `Money.to_integer_exp/1`.  This function converts an integer form of money (including any decimal digits) into a `Money` struct. This is useful for services that return money in an integer format.

```
  iex> Money.from_integer(20000, :USD)
  #Money<:USD, 200.00>

  iex> Money.from_integer(200, :JPY)
  #Money<:JPY, 200>
```
### Roundtrip version

Note that while not documented there is also a "round trip" version called `Money.from_integer/1`.  So you can:

```
iex> Money.new(:USD, 200) |> Money.to_integer_exp |> Money.from_integer
#Money<:USD, 200.00>
```
