### ISSUE TITLE
Implement the Gringotts.Money protocol

### ISSUE THREAD

**Issue by oyeb** [kipcole9/money#47]
The draft of the protocol is ready, please take a look [here](https://github.com/aviabird/gringotts/blob/protocol-expansion/lib/gringotts/money.ex)! If you have any suggestions, please mention them on [issue 85](https://github.com/aviabird/gringotts/issues/85) of `gringotts`.

I've added an implementation for the `Money` type in [`Gringotts.Money`](https://github.com/aviabird/gringotts/blob/protocol-expansion/lib/gringotts/money.ex#L95), but it's best implemented in `ex_money`.
The implementation just about works, but I'm sure you'll be able to come up with something more elegant 😃

**Comment by kipcole9** [comment]
Thanks team.  I’ve implemented the protocol in ex_money on GitHub in the gringotts branch.  And made a few observations on issue #85.

**Comment by kipcole9** [comment]
Have you been able to validate the protocol implementation I added?

**Comment by oyeb** [comment]
Yes, we have and it works splendidly!
The only problem is that we can't automatically  test   your implementation :slightly_frowning_face:

Since `ex_money` is a dependency in our `test` env, it gets compiled before `Gringotts.Money` so your protocol implementation is "not available" in _our_ `test` env.
Our current workaround is to build a separate elixir app which depends on `gringotts` and `ex_money`, and test your implementation in there. Is there a better way to do this -- test a remote implementation without meddling dependencies?

**Comment by kipcole9** [comment]
I use the same approach you do: I have a separate testing app for those areas where I need a different dependency tree.  I haven't found a better approach.

If you are ok I will merge my `gringotts` branch into master to be part of my upcoming 1.4 release.  **What version of Gringotts is the release that I need to depend on?**

**Comment by oyeb** [comment]
`Gringotts.Money` will feature in `1.1.0-alpha` which we will release soon.
Eager to see this on `ex_money` `master`!

**Comment by kipcole9** [comment]
Merged the gringotts branch into master since Gringotts 1.1 supports the protocol.  Pending testing by the Gringotts team before closing this issue and release.

**Comment by kipcole9** [comment]
Pushed [ex_money version 2.6.0](https://hex.pm/packages/ex_money) with the Gringotts protocol implemented.
