### ISSUE TITLE
Proposal: Money.known_iso_currencies/0; Money.current_currency_codes/0;  Money.territory_current_currencies

### ISSUE THREAD

**Issue by kipcole9** [kipcole9/money#50]
With the inclusion of ISO 4217 currencies from the [ISO list](https://www.currency-iso.org/dam/downloads/lists/list_one.xml) in place I've been able to do some analysis of the differences between Cldr currency data and ISO currency data.

### Differences between Cldr currency data and ISO currency data

* ISO 4217 defines 178 currency codes
* Cldr has 300 currencies defined
* The differences are largely historical - ISO 4217 maintains codes in use, CLDR maintains history code information.  Examples would be all the national currencies of the EU before currency integration but there are many others.
* Cldr also defines the currencies in use in a territory (country/state/administrative division).  It also tracks the historic uses of currency over time.  For example:
```elixir
iex> Cldr.Config.territory_info "FR"
%{
  currency: [
    EUR: %{from: ~D[1999-01-01]},
    FRF: %{from: ~D[1960-01-01], to: ~D[2002-02-17]}
  ],
  gdp: 2699000000000,
  ...
```

### Proposed additions to `Money` for version 2.2.0

Therefore I propose adding 2 functions to `Money` that I think will aid implementers:

* `Money.known_iso_currencies/0` which will return the currency codes know to ISO.  This is assumed to return only those currencies in active use, therefore a more practical source of currency codes for many uses.

* `Money.current_currency_codes/0` would return a list of currency codes in use based upon territory definitions.

* Money.territory_current_currencies/0 would return a mapping of territories to their current currency(currencies).

* `Money.territory_current_currencies/1` would return the current currency(currencies) in use for a given territory.

### Purpose for introduction

`Money` is likely to be used as part of transaction system, currency conversion, e-commerce platform or payment gateway.  An implementer may have legal, policy or commercial reason to limit or restrict the territories with which they do business.  Or may choose to limit the currencies in which they trade.  The functions above are intended to simplify the identification and selection of currency data to support such implementations

### Feedback is requested

Your feedback and suggestions are most welcome on this issue or on any feature request you have.

**Comment by kipcole9** [comment]
As of [this commit](https://github.com/kipcole9/money/commit/2c7850e1b7aa2743ddc30b9010e2f47593aeb4da)  the following is added (from the changelog)

### Enhancements

* Add `Money.known_currencies/0` which delegates to `Cldr.known_currencies/0` and returns the list of known currency codes

* Add `Money.known_current_currencies/0` to return the list of currencies currently active according to ISO 4217

* Add `Money.known_historic_currencies/0` to return a list of currencies known to Cldr but which are not considered in current use

* Add `Money.known_tender_currencies/0` to return a list of currencies defined as legal tender in Cldr

* Add the configuration key `:json_library` that specifies which json library to use for decoding json.  The default is `Cldr.Config.json_library/0` which is currently `Poison` although this is likely to change to `Jason` when `Phoenix makes this change.

* Moves the protocol implementations for `String.Chars`, `Inspect` and `Phoenix.HTML.Safe` to a separate file so that recompilation on locale configuration change works correctly.

**Comment by danschultzer** [comment]
Sounds good to me 👍

**Comment by kipcole9** [comment]
The relevant functions have been [added with this commit](https://github.com/kipcole9/money/commit/2c7850e1b7aa2743ddc30b9010e2f47593aeb4da).
