### ISSUE TITLE
API Usage examples outdated / broken

### ISSUE THREAD

**Issue by mbenatti** [kipcole9/money#57]
Hello, I'm playing with your library and I got something broken,
I tried to run this example `Money.to_string Money.new("USD", "234.467"), locale: "fr"`
but with "pt" in locale, I got: 

```
Money.to_string Money.new("USD", "234.467"), locale: "pt"
** (FunctionClauseError) no function clause matching in Money.to_string/2    
    
    The following arguments were given to Money.to_string/2:
    
        # 1
        {:error, {Money.Invalid, "Unable to create money from \"USD\" and \"234.467\""}}
    
        # 2
        [locale: "pt"]
    
    Attempted function clauses (showing 1 out of 1):
    
        def to_string(%Money{} = money, options)
    
    (ex_money) lib/money.ex:415: Money.to_string/2
```
Why I can't use String as currency code??

**Comment by kipcole9** [comment]
@mbenatti, apologies for the inconvenience.  The reasoning is that `Money.new/2` allows the parameters in either order to facilitate piping.  It they are both binaries I can't use a guard to tell which order the params are in.  Its possible this was not a good design choice but given its in a stable release I can't reasonable change that, if at all, until version 2.0.

I could test if one of the parameters is a valid currency code in binary form and make the assumption about the parameter order and I think thats the right thing to do to be consistent.

I'll add that and release a new patch version in the next hour or so.

**Comment by kipcole9** [comment]
A new release 2.2.2 has been pushed to hex.  If you:
```
mix deps.update ex_money
```
I believe the code is back in alignment with the documentation.

**Comment by mbenatti** [comment]
@kipcole9 Thanks, I'll test it soon
