### ISSUE TITLE
Precision for Money.Sigil with Ecto

### ISSUE THREAD

**Issue by scmx** [kipcole9/money#66]
Hi, cool library! 👍

I'm writing a test where I'm asserting that a struct/map with a money field comes out of the database the same as it goes in.
```elixir
@valid_attrs %{balance: ~M[1234.5]SEK}
# ...
test "list_transactions/0 returns all transactions" do
  transaction = transaction_fixture()
  assert list_transactions() == [transaction]
end
```
However I'm noticing that the Money.Ecto.Composite.Type always returns the money with a precision of 8 (which is nice), but if I'm gonna assert equality between input and output, I'll have to specify a precision of 8 in the input as well for the equality to pass. 🤔 
```sh
Assertion with == failed
left:  [%Transaction{balance: #Money<:SEK, 1234.50000000>}
right: [%Transaction{balance: #Money<:SEK, 1234.5}
```
.. but I did solve this for my use case by wrapping the sigil to always have a precision of 8 as seen below.
```elixir
defmodule MoneyEctoSigil do
  @doc ~S"""
  Tweaks the sigil `~M` from Money.Sigil to always have a precision of 8.

  ## Example
      iex> import MoneyEctoSigil
      iex> ~M[1000]usd
      #Money<:USD, 1000.00000000>
      iex> ~M[1000.34]usd
      #Money<:USD, 1000.34000000>
  """

  def sigil_M(amount, [_, _, _] = currency) do
    money = Money.Sigil.sigil_M(amount, currency)
    Map.put(money, :amount, Decimal.round(money.amount, 8))
  end
end
```

I'd be happy to submit a patch if you'd like this function exposed from `Money` somehow, perhaps as `Money.Ecto.Sigil`.

Either way, here's this documented if someone else might find it useful. 😊

**Comment by LostKobrakai** [comment]
You probably should use `Money.equal?/2` to compare money values instead of matching them.

**Comment by kipcole9** [comment]
@scmx thanks for the issue and the suggestions.  The `Money.Ecto.Composite.Type` precision of `(20,8)` is really an implementation detail and shouldn't be assumed. In fact with at least one crypto currency the required precision is `12`.  Indeed the `(20,8)` precision is a default implementation; users are free to define the type any other way they like (and take responsibility for it too 😃)

Also, as @LostKobrakai notes, pattern matching for equality on maps, records, tuples and lists is often likely to return "surprising" results.

Therefore I support the suggestion that you use `Money.equal?/2` to determine equality.  Or `Money.compare/2` in other comparison cases.
