### ISSUE TITLE
Add Money.currency_select/4

### ISSUE THREAD

**Issue by Schultzer** [kipcole9/money#70]
Hi Kip,

I could see this as a useful function in Money let me know what you think

```elixir
  if Code.ensure_loaded?(Phoenix.HTML) do
    @type currency_select_options :: [{:currencies, list(atom() | binary())} | {:mapper, function()} | {:locale, String.t() | Cldr.LanguageTag.t()}]
    @doc """
    A helper method to genereate a currency select for a `Phoenix.HTML.Form.t`
    for select options see `Phoenix.HTML.Form.select/4`

    * `Options` are expected to be an `Keyword.t` with the following keys
      * `:currencies` defualts to `Cldr.known_currencies/1`
      * `:mapper`     defualts to `&({&1.code <> " - " <> &1.name, &1.code})`
      * `:locale`     defualts to `Cldr.default_locale/1`

    # Example
       => Money.currency_select(my_form, :currency, [selected: :USD])
       => Money.currency_select(my_form, :currency, [selected: "USD"], ["USD", "EUR", :JPY], &({&1.code <> " - " <> &1.name, &1.code}))
    """
    @spec currency_select(Phoenix.HTML.Form.t, atom() | binary(), list(), currency_select_options) :: Phoenix.HTML.safe()
    def currency_select(form, field, select_options \\ [], options \\ [])
    def currency_select(form, field, select_options, options) do
      options = defualt_options(options)
      Phoenix.HTML.Form.select(form, field, currency_options(options), select_options)
    end

    defp defualt_options(options) do
      options
      |> Keyword.put_new(:currencies, known_currencies())
      |> Keyword.put_new(:mapper, &({&1.code <> " - " <> &1.name, &1.code}))
      |> Keyword.put_new(:locale, Cldr.default_locale())
    end

    defp currency_options([[currencies: currencies, mapper: mapper, locale: locale] | _rest]) do
      currencies
      |> Enum.map(&Currency.currency_for_code(&1, locale))
      |> Enum.map(fn {:ok, currency} -> mapper.(currency) end)
      |> Enum.sort()
    end
  end
```

**Comment by LostKobrakai** [comment]
I like the idea, but I'd like to see a helper library for it like phoenix_html (ex_cldr_html maybe?) instead of putting it in the core library. This way it could include more units than just currencies and be used without actually using ex_money. Someone might just store the favorite currency for a user, but not deal with money further than that.

**Comment by kipcole9** [comment]
I like that idea @LostKobrakai.  I can see value in a lib that provides HTML helpers for currency, locale, territory and other data and thats the approach I intend to take.  I like the idea of calling it `ex_cldr_html` to be consistent with the `phoenix_html` approach.

**Comment by kipcole9** [comment]
Am working on `ex_cldr_html` but that pace isn't rapid.  Should have it on GitHub on 20th May.  At which time I will close this issue in favour of the new repo.

**Comment by Schultzer** [comment]
Let me know if there is anything I can help with?

**Comment by kipcole9** [comment]
Apologies for taking so long.  An initial version (basically packaging your code) is [now on GitHub](https://github.com/kipcole9/cldr_html).

Basically I have:
1. Extracted the module `Cldr.Currency` into its [own package](https://hex.pm/packages/ex_cldr_currencies)
2. Updated [ex_cldr_numbers](https://hex.pm/packages/ex_cldr_numbers) to use the extracted package
3. Used [ex_cldr_currencies](https://hex.pm/packages/ex_cldr_currencies) as an optional dependency for `ex_cldr_html`.

The idea now is to:
1. Add tests and update docs
2. Look at options to restrict the list of currencies displayed
3. Look at options to use only current currencies, historical ones or both

Then after 1.0 release
1. Add similar functions for territories, ....

Let me know what you think, I'll get this up to a releasable package this week.

**Comment by kipcole9** [comment]
Also I'll close this issue - please add any comments on the [new repo](https://github.com/kipcole9/cldr_html)
