### ISSUE TITLE
Extract SQL queries for migrations into their own files

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [kipcole9/money#73]
Hello,
This is a suggestion and not a bug report.

Not everyone want to use phoenix or want to use ecto migrations, which ties DB to elixir.
As a general suggestion, can you extract the "SQL" part (the create type/drop and the creation of aggregate functions) into their own files and read those? It would make extremely easier writing a psql script that just loads your function (or using alternative migration tools).

Thanks for this amazing library by the way, I've been reading it and it's incredibly in depth!

**Comment by kipcole9** [comment]
Great idea, I'll get that done over the weekend!

**Comment by Fire-Dragon-DoL** [comment]
Hey @kipcole9 , if you want I can submit a PR for it!

**Comment by kipcole9** [comment]
I have [added a commit](
https://github.com/kipcole9/money/commit/3e76e91a0987dddb975f93240eec8b1fc82c4ff) which implements your suggestion.  See the module `Money.DDL`.

I need to run some tests in my separate test app (which tests DB functionality) before pushing a new release.

Feedback is welcome.

**Comment by Fire-Dragon-DoL** [comment]
@kipcole9 looks exactly what I had in mind. One note: the SQL files are missing from the commit. Are they in a separate one? `priv` is in gitignore, probably it's that

**Comment by kipcole9** [comment]
Well spotted - push a commit to add them in.  A couple of things I have to check:

1. The quoting inside an eex template isn't something I've explored so I may have to `inspect` the strings to get quoted strings

2. Sometime Postgres is picky about multiple DDL commands in a single transaction so I may have to split them out in a couple of cases.

**Comment by Fire-Dragon-DoL** [comment]
Oh right, the **1** might be annoying

**Comment by kipcole9** [comment]
Fixed "1" in the latest commit.

**Comment by Fire-Dragon-DoL** [comment]
That looks perfect!

**Comment by kipcole9** [comment]
[Version 2.7.0](https://hex.pm/packages/ex_money) released on Hex.  Thanks for the suggestion and support.

**Comment by Fire-Dragon-DoL** [comment]
Thanks for the speed, amazing!
