### ISSUE TITLE
Conversion rate helper rate_between/2

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/money#78]
When I convert money between currencies I need to surface the used conversion rate to the invoices I'm generating. For that it would be nice to have an helper like `Money.Currency.get_conversion_rate(from_currency, to_currency, rates \\ …) :: Decimal.t`. With Decimal values it shouldn't matter if `Money.to_currency` does `amount / from_currency_rate * to_currency_rate` or `amount * (to_currency_rate / from_currency_rate)` if I understand them correctly, and the part in parenthesis could be what `get_conversion_rate` does.

**Comment by kipcole9** [comment]
Added `Money.cross_rate/3` and `Money.cross_rate!/3`.  Let me know if that meets your requirement?  If so I will release it to hex.

**Comment by LostKobrakai** [comment]
Seems like exactly what I described, thanks :)

**Comment by kipcole9** [comment]
Published to hex as [Money version 2.9.0](https://hex.pm/packages/ex_money)
