### ISSUE TITLE
Trouble creating money from string currency

### ISSUE THREAD

**Issue by imranismail** [kipcole9/money#8]
How to reproduce

```
iex> Money.new("USD", 100) 
** (ArgumentError) argument error
               :erlang.binary_to_existing_atom("USD", :utf8)
               lib/cldr/currency.ex:121: Cldr.Currency.normalize_currency_code/1
    (ex_money) lib/money.ex:128: Money.new/2
```

What works is if the atom already exist

```
iex> :USD
:USD
iex> Money.new("USD", 100) 
#Money<:USD, 100>
```

**Comment by kipcole9** [comment]
The bug was triggered in the case where the list of atoms representing valid ISO4277 currency codes was not loaded when the request to create new money struct was made.  The list of atom currency codes is now force loaded at compile time.  Sorry for the inconvenience.
