### ISSUE TITLE
Have an valid empty state for ecto money types

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/money#80]
Currently when using the built in ecto types of ex_money any "empty" state will result in a casting error, which is hard to handle in a normal changeset flow. I'd be happy to have  the following so if both fields are empty it's not raising:
`def cast(%{"currency" => "", "amount" => ""}), do: {:ok, nil}`. 

Maybe even:
`def cast(%{"currency" => currency, "amount" => ""}), do: {:ok, Money.zero(currency)}`. 

I feel like ecto type should be preprered for empty values and just let the user explicitly require values via `validate_required/3` / `validate_change/3`.

**Comment by kipcole9** [comment]
I feel like `%{"currency" => "", "amount" => ""}` is an error since the money type is malformed.  And therefore maybe a `validate_money/3` would be a better idea?  That is, validate in the changeset rather than coerce an invalid `Money` map into a misleading `{:ok, nil}`.

Something like:
```
def validate_money(changeset, field, options \\ []) do
  validate_change(changeset, field, fn _, url ->
    case String.starts_with?(url, @our_url) do
      %Money{} -> []
      %{currency: currency, amount: amount} -> validate currency and amount
      %{"currency" => currency, "amount" => amount} -> validate currency and amount
      _ -> [{field, options[:message] || "Invalid money"}]
    end
  end)
end
```

**Comment by LostKobrakai** [comment]
The problem is that everything that we don't `cast` will raise a cast error and `cast` is explicitly meant to convert outside data to an internal representation. In my opinion not filling out a money/amount field in a html form is the same as sending back an empty textarea. It should work, but result in an empty field (a.k.a. `nil`). If the field is required then I use `validate_required` and I will get a nice "is required" error message (and not a 500 for the raised cast error). The point I want to get to: There needs to be ways for an ecto type to return `{:ok, Money.t} | {:ok, nil} | :error`. There just are legitimate use-cases for `cast` to handle not only valid money input, but also blank input. 

> I feel like %{"currency" => "", "amount" => ""} is an error since the money type is malformed.

I don't feel like that at all. The necessary parts are supplied, but chosen/happen to be empty. That's not malformated, but the blank state.

**Comment by kipcole9** [comment]
Makes sense, i see what you're saying.  I'd prefer to return `{:ok, nil}`.  The idea being that its nil iff amount is empty (`nil` or `""`).  Is that workable for you?

**Comment by LostKobrakai** [comment]
Sure, that was my initial proposed value. The `Money.zero` was for the cases one does only receive an currency, but no amount, but that's certainly debatable if this is good or bad.

**Comment by kipcole9** [comment]
I've updated along the lines of your suggestion.  Let me know if it reflects what you were after?  If so I'll release on hex today.  Thanks again for the report and suggestion.
