### ISSUE TITLE
Money.to_string breaks the type spec of Cldr.Money.to_string

### ISSUE THREAD

**Issue by amuino** [kipcole9/money#81]
`Money.to_string` calls `Cldr.Number.to_string` with a `Decimal.t`, but the typespec for `Cldr.Number.to_string` expects a `number()`.

This causes a warning in dialyzer, although the code "just works".

Not sure if this should be fixed on Money (by converting the decimal to a number first) or in Number (by changing the `@spec` to accept `number() | Decimal.t` as input)

**Comment by kipcole9** [comment]
@amuino Thanks for the bug report.  Fixed and released in [Cldr Numbers version 1.5.2](https://hex.pm/packages/cldr_numbers) on the type spec for `Cldr.Number.to_string/2`.
