### ISSUE TITLE
Application is not loaded for prod release w/ Distillery 2.0

### ISSUE THREAD

**Issue by A-Legg** [kipcole9/money#82]
Thanks so much for all of your hard work on these libraries!

While attempting to build a production release via distillery it appears the application is not loaded as I am getting the following error: 
```
Recompiling 15 modules from [:ex_cldr, :ex_cldr_currencies, :ex_cldr_numbers, :ex_money]
Generating Cldr for 2 locales named ["en", "root"] with a default locale named "en"
==> Assembling release..
==> Building release foo:0.0.1 using environment prod
==> Release failed: function nil.name/0 is undefined
    nil.name()
    (distillery) lib/mix/lib/releases/models/release.ex:532: Mix.Releases.Release.do_add_app/4
    (distillery) lib/mix/lib/releases/models/release.ex:547: Mix.Releases.Release.do_add_children/4
    (distillery) lib/mix/lib/releases/models/release.ex:507: Mix.Releases.Release.add_apps/3
    (distillery) lib/mix/lib/releases/models/release.ex:476: Mix.Releases.Release.apps/1
    (distillery) lib/mix/lib/releases/models/release.ex:330: Mix.Releases.Release.apply_configuration/3
    (distillery) lib/mix/lib/releases/assembler.ex:28: Mix.Releases.Assembler.pre_assemble/1
    (distillery) lib/mix/lib/releases/assembler.ex:46: Mix.Releases.Assembler.assemble/1
```
It is failing on https://github.com/bitwalker/distillery/blob/master/lib/mix/lib/releases/models/app.ex#L48
which is the case when the application isn't loaded. From the Application module docs:
```
 @spec spec(app(), key()) :: value() | nil

Returns the value for key in app's specification.

See spec/1 for the supported keys. If the given specification parameter does
not exist, this function will raise. Returns nil if the application is not
loaded.
```

I've got the cldr dep being compiled last: `compilers: [:phoenix, :gettext] ++ Mix.compilers() ++ [:cldr]`  and everything works in development and test environments. Additionally, I've attempted to include `ex_money` and its cldr dps in the applications list without success. 

Any ideas as to what could be the cause?

**Comment by kipcole9** [comment]
@A-Legg I wish I had a clear and specific answer but I don't.  An need to dive more into releases and Distillery 2.0  I wonder if @LostKobrakai has any thoughts or suggestions?

One small thought - try omitting the `:cldr` compiler?  Its a wart on the code until I can finish up `Cldr version 2` by the end of the year.  So its worth seeing if removing that makes any difference.

I won't be able to work on replicating the real issue until the weekend, but I will work on it then.

Apologies for the inconvenience, I'll get on it.

**Comment by LostKobrakai** [comment]
I'm still on distillery v1 with my projects using ex_money/cldr.

**Comment by kipcole9** [comment]
Thanks for answering - I’ll work on Distillery v2 on the weekend and report back.

**Comment by kipcole9** [comment]
I should note that when replacing the `:group` and `:decimal` symbols the code will always use the `Latn` number system since thats the only digit input possible in Elixir.  I could transliterate the digits from another number system to the `Latn` system but I think that would be quite computationally expensive (I do transliteration from latin to other number systems when formatting but thats an explicit choice).

**Comment by A-Legg** [comment]
@kipcole9 @LostKobrakai Thanks so much for the timely response, I really appreciate it. Looking forward to the next release, please let me know if I can be of any assistance.

**Comment by kipcole9** [comment]
There's a small (quite small) chance that an issue report on [ex_money](https://github.com/kipcole9/money) may be related to this issue.  [This comment](https://github.com/kipcole9/cldr/issues/78#issuecomment-430491666) on the issue thread explains what you can try if you're willing to give it a go.

Basically, configure a test branch of `ex_cldr` in your `mix.exs`:
```elixir
defp deps do
  [
    {:ex_cldr, git: "https://github.com/kipcole9/cldr", branch: "issue_78", override: true},
    ...
  ]
end
```
As I said, there's a small chance your issue and this are related so would be curious to see if this helps you too.

**Comment by kipcole9** [comment]
I have recently released a new release of [ex_money](https://hex.pm/packages/ex_money/3.0.0) which uses a new version of [ex_cldr](https://hex.pm/packages/ex_cldr/2.0.4) which I think will make release management more predictable.  I'd be interested to see if this release fixes this issue.  Basically the structure of the underlying `ex_cldr` aligns much better with how `Gettext`, `Ecto` and `Phoenix` generate code into a user-defined backend module which is a much cleaner architecture.

**Comment by A-Legg** [comment]
Thanks, we were able to successfully update to 3.0!
