### ISSUE TITLE
Usage with Phoenix Forms

### ISSUE THREAD

**Issue by dhruvbhatia** [kipcole9/money#92]
Great library - hopefully this q isn't out of scope:
**How would one integrate Money with Phoenix forms?**

Let's say I have `field :amount, Money.Ecto.Composite.Type`  within my schema.. are there any helpers that will produce the relevant form fields for the `currency` and `amount` values?

Help appreciated.

**Comment by LostKobrakai** [comment]
Personally I'd say it's out of scope to be included in the library. But that's not so say there couldn't be a `ex_money_html` library. 

The biggest issue here is that phoenix is trying to handle a money field as a single field, but it needs to be two inputs, which is why you need to customize a few things like the naming of fields or how values are filled in. I feel like the better solution here is having a schemaless changeset for your frontend form, which just maps the money value to two separate fields, which phoenix should have a way easier time to handle. On submission the controller could then consolidate the submitted values again.

**Comment by LostKobrakai** [comment]
> I haven't dived into HTML for a while but I did some googling and it seems that there's no consistent way to approach money in an HTML form.

I'm using two separate inputs for money. A select for choosing the currency and a number input for the amount. But having a simple text -> money option would be great as it would work with a single input, which is easier to map for phoenix form helpers.

**Comment by kipcole9** [comment]
I have added `Money.parse/2` and published [ex_money version 3.2.0](https://github.com/kipcole9/money/releases/tag/v3.2.0) to [hex](https://hex.pm/packages/ex_money/3.2.0).

This allows you to parse the following types of input:
```
# Leading currency code
iex> Money.parse("USD 100")
#Money<:USD, 100>

# Localised number input
iex> Money.parse "USD 100,00", locale: "de"
#Money<:USD, 100.00>

# Trailing currency code
iex> Money.parse("100 USD")
#Money<:USD, 100>

iex> Money.parse("100")
{:error,
  {Money.Invalid,
  "A currency code must be specified but was not found in \"100\""}}

# Parsing is quite strict, additional text fails the parse
iex> Money.parse("USD 100 with trailing text")
{:error, {Money.Invalid, "Could not parse \"USD 100 with trailing text\"."}}
```

**Comment by kipcole9** [comment]
I have added basic support for `changesets` using `cast/4` which in turn provides basic support for HTML forms. Find it as [ex_money version 3.2.1](https://github.com/kipcole9/money/releases/tag/v3.2.1) to [hex](https://hex.pm/packages/ex_money/3.2.1).

### Bug Fixes

* Added `Money.Ecto.Composite.Type.cast/1` and `Money.Ecto.Map.Type.cast/1` for a `String.t` parameter. When a `String.t` is provided, `cast/1` will call `Money.parse/2` to create the `Money.t`.

* `Money.new/3` now uses the current locale on the default backend if no locale or backend is specified. This means that `Money.Ecto.Composite.Type.cast/1` and `Money.Ecto.Map.Type.cast/1` will be parsed using the locale that has been set for the current process in the default backend. As a result, a simple `type=text` form field can be used to input a money type (currency code and amount in a single string) that can then be cast to a `Money.t`.

### Casting a money type (basic support for HTML forms)

`Money` supports form field inputs that are a single string combining both a currency code and an amount.  When a form field (or other data) is [cast](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast/4) then `Money` will attempt to parse a string field into a `Money.t` using `Money.parse/2`. Therefore simple money form input can be supported with a single input field of `type=text`.

Note that when parsing the input text, the amount is interpreted in the context of the current locale set on the default backend configured for `ex_money`.  This affects how separator characters are interpreted in exactly the same way as is done for `Money.new/3`.

**Comment by dhruvbhatia** [comment]
Thank you, this is great!

I've run into a casting issue when using Aussie dollar amounts: the `type="text"` form field seems to render my `Money` value in a different format to what `Money.cast/1` expects.

E.g. My form field renders values as `A$35.50` whereas `Money.cast/1` (and subsequently `Money.parse`) expect a value of `AUD $35.50` as demonstrated below:

```elixir
iex(1)> Money.parse("A$35.50") # default field format fails
{:error, {Money.Invalid, "Could not parse \"A$35.50\"."}}
iex(2)> Money.parse("AUD 35.50") # however this format works
#Money<:AUD, 35.50>
```
Is this a bug? Or is there a configuration option that will allow my text form fields to render in the proper `AUD xx` format instead of the `A$xx` format which fails while casting?

**Comment by dhruvbhatia** [comment]
Thanks @kipcole9 - appreciate it!

**Comment by kipcole9** [comment]
@dhruvbhatia Getting close now.  Parsing is now down against all the known strings that [CLDR](https://cldr.unicode.org) has available. Therefore it can also parse in a locale appropriate way.  I still need to finish up documentation and tests.  But here are a few example:
```
iex> Money.parse "$au 12 346", locale: "fr"
#Money<:AUD, 12346>
iex> Money.parse "12 346 dollar australien", locale: "fr"
#Money<:AUD, 12346>
iex> Money.parse "A$ 12346", locale: "en"                   
#Money<:AUD, 12346>
iex> Money.parse "australian dollar 12346.45", locale: "en"
#Money<:AUD, 12346.45>
iex> Money.parse "AU$ 12346,45", locale: "de"     
#Money<:AUD, 12346.45>

# Can also return the strings available for a given currency
# and locale
iex> Cldr.Currency.strings_for_currency :AUD, "de"         
["aud", "au$", "australischer dollar", "australische dollar"]
```

Should have things wrapped up by the end of the weekend.

**Comment by kipcole9** [comment]
Updated to [version 3.2.2](https://github.com/kipcole9/money/releases/tag/v3.2.2) and pushed to [hex](https://hex.pm/packages/ex_money/3.2.2).

Thanks for raising the issue. Been an interesting challenge to keep it simple but as complete as possible.  Let me know if you see any issues, I'll keep this open for a little while.

**Comment by dhruvbhatia** [comment]
Thanks once again. :)
Does hex take a while to propagate? I'm seeing the latest version as `v3.2.1` and the link above gives a 404?

**Comment by kipcole9** [comment]
Whoops.  Forgot to actually publish to hex. It's there now.  Sorry 'bout that.

**Comment by kipcole9** [comment]
It should pull in the right dependencies but just in case you may need to:
```
mix deps.update ex_cldr ex_cldr_currencies
```
