### ISSUE TITLE
Multiplying 0 by -1 results in negative 0?

### ISSUE THREAD

**Issue by coladarci** [kipcole9/money#93]
This is most likely not a bug in Money, itself, but I'm really curious why this happens...

Notice `$0.00` turns into `-0.00` the moment it's multipled by a negative number? Odd!
 
```
iex> Money.new!(:USD, "0.00") |> Money.mult!(1) |> Money.to_string()
{:ok, "$0.00"}
iex> Money.new!(:USD, "0.00") |> Money.mult!(-1) |> Money.to_string()
{:ok, "-0.00"}
```

**Comment by coladarci** [comment]
For context, we basically have to do this type of thing in our own code to prevent some 0s being positive and some being negative:
```
  defp safe_mult!(%Money{amount: %Decimal{coef: 0}} = money, _mult), do: money
  defp safe_mult!(%Money{} = money, mult), do: Money.mult!(money, mult)
```

**Comment by coladarci** [comment]
That's a great question around why it's a problem - it's actually only because of `Money.to_string`. If you are showing a price-breakdown of something to a client and there are a bunch of 0 elements (discounts, fees, whatever) and some are displayed as "$0.00" and some are displayed as "-0.00" it creates confusion. 

So to your point, it's specifically around formatting these values. So the feature request would be something along the lines of "When invoking `Money.to_string` treat all Zeros the same (I'd vote for positive)"

**Comment by LostKobrakai** [comment]
That's surely a valid usecase, but I'd vote for leaving the current, more correct, behaviour by default (people might print out money values to debug things), but have an option to force a certain sign on zero amounts.

**Comment by LostKobrakai** [comment]
https://github.com/kipcole9/money/pull/94/files let's see what @kipcole9 thinks about it.
