### ISSUE TITLE
Formatting glitch in ExDocs documenation

### ISSUE THREAD

**Issue by fireproofsocks** [kipcole9/money#99]
Scroll down to https://hexdocs.pm/ex_money/readme.html#postgres-database-functions
-- the regular text is formatted as code, and that makes it hard to read.

**Comment by kipcole9** [comment]
Thanks for the report @fireproofsocks and for the fix @LostKobrakai.  [Updated on GitHub](https://github.com/kipcole9/money/releases/tag/v3.4.1) and [pushed to hex](https://hex.pm/packages/ex_money/3.4.1).
